apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-prod
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: tech-trends/helm
    repoURL: https://github.com/asharn/Shell-Software-Engineer-Train-to-Hire-Scholarship-Program
    targetRevision: HEAD