name: TechTrends - Package with Docker

on:
  push:
    branches:
      - main

jobs:
  package-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./tech-trends
          file: ./tech-trends/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/techtrends:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}